function _ssh_agent_start -d "Start a new ssh agent"
    set -xg SSH_ENV "$HOME/.ssh/ssh-agent-env"
    # We use the -c flag to generate csh-style output of the form:
    # setenv SSH_AUTH_SOCK ...
    # This output is then converted to fish-style output.
    set -l ssh_output (ssh-agent -c)
    set ssh_output (string match -r -v '^echo' "$ssh_output")
    set ssh_output (string replace 'setenv' 'set -gx' -- "$ssh_output")
    set ssh_output (string replace -r ';\s*$' '' -- "$ssh_output")
    set ssh_output "# Generated by fish-ssh-agent" "$ssh_output"
    printf "%s\n" "$ssh_output" >"$SSH_ENV"
    chmod 600 "$SSH_ENV"
    source "$SSH_ENV"
end
