function _ssh_agent_start --description "Start a new ssh agent"
    set -l lock_file "$SSH_ENV_FILE.lock"

    # Race Condition Handling:
    # We use a directory lock (mkdir is atomic) to ensure only one shell starts the agent.
    # If we fail to get the lock, we wait for the other process to finish.
    if not mkdir "$lock_file" 2>/dev/null
        for i in (seq 1 20) # Wait up to 2 seconds
            if test -f "$SSH_ENV_FILE"
                source "$SSH_ENV_FILE" >/dev/null 2>&1
                ssh-add -l >/dev/null 2>&1
                if test $status -eq 0; or test $status -eq 1
                    return 0
                end
            end
            sleep 0.1
        end
        # Timeout: Assume stale lock, remove it and proceed to start a new agent.
        rmdir "$lock_file" 2>/dev/null
    else
        # Lock acquired.
        # Double-check: Another process might have finished just before we got the lock.
        if test -f "$SSH_ENV_FILE"
            source "$SSH_ENV_FILE" >/dev/null 2>&1
            ssh-add -l >/dev/null 2>&1
            if test $status -eq 0; or test $status -eq 1
                rmdir "$lock_file"
                return 0
            end
        end
    end

    # Start the agent
    # We use the -c flag to generate csh-style output of the form:
    # setenv SSH_AUTH_SOCK ...
    # This output is then converted to fish-style output.
    set -l agent_output_csh (ssh-agent -c)
    set -l agent_output_fish

    for line in $agent_output_csh
        if string match --quiet --regex '^echo' -- $line
            continue
        end
        set -l transformed (string replace 'setenv' 'set -gx' -- $line)
        set transformed (string replace --regex ';(\s*)$' '' -- $transformed)
        set --append agent_output_fish $transformed
    end

    if test (count $agent_output_fish) -eq 0
        rmdir "$lock_file"
        echo "Failed to start ssh-agent"
        return 1
    end

    set --prepend agent_output_fish "# Generated by fish-ssh-agent"
    printf "%s\n" $agent_output_fish >"$SSH_ENV_FILE"
    chmod 600 "$SSH_ENV_FILE"
    source "$SSH_ENV_FILE"
    rmdir "$lock_file"
    echo "Started new SSH agent. Run 'ssh-add' to add keys."
end
